[build-system]
    requires = ["flit_core >=3.2,<4"]
    build-backend = "flit_core.buildapi"

    [project]
    name = "project_template"
    authors = [
        {name = "MFJess", email = "a93318@alunos.uminho.pt"},
    ]

    classifiers = [
        "License :: OSI Approved :: MIT License",
    ]
    
    requires-python = ">=3.8"
    dynamic = ["version", "description"]
    dependencies = []  

    [project.scripts]
    projectTemplate = "project_template:main"
